version: '3'
services:
    api:
      build: api/.
      ports:
        - "8080:8080"
      links:
        - mysql
      environment:
        MYSQL_DB_HOST: mysql
        MYSQL_DB_USER: root
        MYSQL_DB_PWD: root

    event:
      build: event/.
      links:
        - mysql
      environment:
        MYSQL_DB_HOST: mysql
        MYSQL_DB_USER: root
        MYSQL_DB_PWD: root

    mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./scripts/mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql