version: '3'
services:
    api:
      build: api/.
      ports:
        - "8080:8080"
      depends_on:
        - mysql
        - kafka
      environment:
        MYSQL_DB_HOST: mysql
        MYSQL_DB_USER: root
        MYSQL_DB_PWD: root

    event:
      build: event/.
      links:
        - mysql
      environment:
        MYSQL_DB_HOST: mysql
        MYSQL_DB_USER: root
        MYSQL_DB_PWD: root

    mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./scripts/mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

    zookeeper:
      image: debezium/zookeeper
      ports:
        - "2181:2181"

    kafka:
      image: debezium/kafka
      ports:
        - "9092:9092"
      environment:
        ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_DELETE_TOPIC_ENABLE: "true"
      depends_on:
        - "zookeeper"