version: '3'
services:
    api:
      build: api/.
      ports:
        - "8080"
      links:
        - mysql
    mysql:
      image: mysql
      ports:
        - "3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./scripts/mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql